AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Static Website para Angular

Parameters:
  SiteBucketName:
    Type: String
    Description: Nombre único del bucket (ej: btg-funds-site-123)

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SiteBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${SiteBucketName}/*

Outputs:
  WebsiteURL:
    Value: !GetAtt SiteBucket.WebsiteURL
  BucketName:
    Value: !Ref SiteBucket
