spring:
  application:
    name: funds-btg

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: btgdb

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG